trigger:
  - azure-pipelines-1
resources:
  repositories:
    - repository: templates-azure-devops
      type: github
      name: rfurtad/templates-azure-devops
      endpoint: github.com_rfurtad
variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'Docker Registry'
  repository: 'kingflare/turbo-todo'
  imagePullSecret: 'testing'
  kubernetesServiceConnection: 'Kubernetes Connection'
stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - template: build-template.yml@templates-azure-devops
      parameters:
        containerRegistry: 'Docker Registry'
        repository: 'kingflare/turbo-todo'
        tag: '$(tag)'
- stage: Deploy
  displayName: Deploy Stage
  jobs:
    - template: deploy-template.yml@templates-azure-devops
      parameters:
        containerRegistry: '$(containerRegistry)'        
        repository: 'kingflare/turbo-todo'
        kubeConnection: 'Kubernetes Connection'
        tag: '$(tag)'
