trigger:
  - master
resources:
  repositories:
    - repository: templates-azure-devops
      type: github
      name: rfurtad/templates-azure-devops
      endpoint: rfurtad
variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'Docker Registry'
  repository: 'kingflare/python-flask-sample'
  imagePullSecret: 'python-flask'
  kubernetesServiceConnection: 'Kubernetes Connection'
stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - template: python-templates/build-template.yml@templates-azure-devops
      parameters:
        containerRegistry: 'Docker Registry'
        repository: '$(repository)'
        tag: '$(tag)'

