trigger:
  - azure-pipelines-1
resources:
  repositories:
    - repository: templates-azure-devops
      type: github
      name: rfurtad/templates-azure-devops
      endpoint: github.com_rfurtad
variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'Docker Registry'
  repository: 'kingflare/python-flask-sample'
  imagePullSecret: 'python-flask'
  kubernetesServiceConnection: 'Kubernetes Connection'
stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - template: build-template.yml@templates-azure-devops
      parameters:
        containerRegistry: 'containerRegistry'
        repository: '$(repository)'
        tag: '$(tag)'

